// ─── CRM Constants ────────────────────────────────────────────────────────────

export const ASESORES = ['Oscar', 'Sofia', 'Angel'] as const;
export type Asesor = typeof ASESORES[number];

export const LEAD_ORIGINS = [
  'Meta Ads',
  'Google Ads',
  'Orgánico',
  'Chatbot Lex',
  'TikTok Ads',
  'Referido',
  'Otro',
] as const;

export const ACTIVITY_TYPES = [
  'Llamada',
  'WhatsApp',
  'Envío de Propuesta',
  'Reunión',
] as const;
export type ActivityType = typeof ACTIVITY_TYPES[number];

export const ACTIVITY_ICONS: Record<string, string> = {
  'Llamada':            '📞',
  'WhatsApp':           '💬',
  'Envío de Propuesta': '📄',
  'Reunión':            '🤝',
};

// 7 etapas del pipeline de ventas
export const CRM_STAGES = [
  { id: 1, nombre: 'Agendamiento Tenida',       color: '#fbbf24', orden: 1, es_ganado: false, es_perdido: false },
  { id: 2, nombre: 'Agendamiento Cerrada',       color: '#3b82f6', orden: 2, es_ganado: false, es_perdido: false },
  { id: 3, nombre: 'Reunión de Cierre Agendada', color: '#f97316', orden: 3, es_ganado: false, es_perdido: false },
  { id: 4, nombre: 'Reunión de Cierre Tenida',   color: '#a855f7', orden: 4, es_ganado: false, es_perdido: false },
  { id: 5, nombre: 'Negocio Pendiente',          color: '#6b7280', orden: 5, es_ganado: false, es_perdido: false },
  { id: 6, nombre: 'Cliente Pagó',               color: '#10b981', orden: 6, es_ganado: true,  es_perdido: false },
  { id: 7, nombre: 'Negocio Perdido',            color: '#ef4444', orden: 7, es_ganado: false, es_perdido: true  },
] as const;

export const ORIGIN_COLOR: Record<string, string> = {
  'Meta Ads':    '#1877F2',
  'Google Ads':  '#4285F4',
  'TikTok Ads':  '#FF0050',
  'Orgánico':    '#fbbf24',
  'Chatbot Lex': '#8b5cf6',
  'Referido':    '#14b8a6',
  'Otro':        '#6b7280',
};

// Todas las ciudades de Colombia (sin duplicados, ordenadas)
export const COLOMBIA_CITIES = [
  // Capitales de departamento
  'Arauca',
  'Armenia',
  'Barranquilla',
  'Bogotá',
  'Bucaramanga',
  'Cali',
  'Cartagena',
  'Cúcuta',
  'Florencia',
  'Ibagué',
  'Inírida',
  'Leticia',
  'Manizales',
  'Medellín',
  'Mitú',
  'Mocoa',
  'Montería',
  'Neiva',
  'Pasto',
  'Pereira',
  'Popayán',
  'Puerto Carreño',
  'Quibdó',
  'Riohacha',
  'San Andrés',
  'San José del Guaviare',
  'Santa Marta',
  'Tunja',
  'Valledupar',
  'Villavicencio',
  'Yopal',
  // Ciudades importantes
  'Agustín Codazzi',
  'Aguachica',
  'Apartadó',
  'Barrancabermeja',
  'Bello',
  'Buga',
  'Campoalegre',
  'Cartago',
  'Caucasia',
  'Cereté',
  'Chaparral',
  'Chigorodó',
  'Chiquinquirá',
  'Chinchiná',
  'Ciénaga',
  'Dosquebradas',
  'Duitama',
  'El Banco',
  'El Cerrito',
  'Envigado',
  'Espinal',
  'Facatativá',
  'Floridablanca',
  'Fundación',
  'Fusagasugá',
  'Garzón',
  'Girardot',
  'Girón',
  'Honda',
  'Ipiales',
  'Itagüí',
  'Jamundí',
  'La Dorada',
  'La Plata',
  'La Unión',
  'La Virginia',
  'Líbano',
  'Lorica',
  'Magangué',
  'Maicao',
  'Mariquita',
  'Mompox',
  'Ocaña',
  'Palmira',
  'Pamplona',
  'Piedecuesta',
  'Pitalito',
  'Puerto Asís',
  'Puerto Tejada',
  'Rionegro',
  'Sahagún',
  'San Agustín',
  'Sandoná',
  'Santa Rosa de Cabal',
  'Sincelejo',
  'Soacha',
  'Sogamoso',
  'Soledad',
  'Tumaco',
  'Tuluá',
  'Turbo',
  'Uribia',
  'Zipaquirá',
  'Otra ciudad',
];
